default_stages: [commit]
default_language_version:
    python: python3.11


repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    -   repo: https://github.com/ecugol/pre-commit-hooks-django
        rev: v0.4.0  # Use the ref you want to point at
        hooks:
            -   id: check-untracked-migrations
                # Optional, if specified, hook will work only on these branches
                # otherwise it will work on all branches
                args: [ "--branches", "main" ]
            -   id: check-unapplied-migrations
            -   id: check-absent-migrations
            -   id: po-location-format
                # Mandatory, select one of the following options:
                # file: show only the file path as location
                # never: remove all locations
                args: [ "--add-location", "file" ]

    -   repo: https://github.com/sourcery-ai/sourcery
        rev: v1.1.0
        hooks:
            -   id: sourcery
                  # The best way to use Sourcery in a pre-commit hook:
                  # * review only changed lines:
                # * omit the summary
                args: [ --diff=git diff HEAD, --no-summary ]

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: "v0.0.257"
      hooks:
          - id: ruff
            args: [--fix]

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id:
                black

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort

    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: 'v8.37.0'  # Use the sha / tag you want to point at
        hooks:
            -   id: eslint
                # *.js, *.jsx, *.ts and *.tsx and .vue files
                files: \.(js|jsx|ts|tsx|vue)$
                types: [ file ]
                args:
                    [
                        --config,
                        frontend/.eslintrc,
                        --fix,
                    ]
    -   repo: https://github.com/pre-commit/mirrors-prettier
        rev: 'v3.0.0-alpha.6'  # Use the sha / tag you want to point at
        hooks:
            -   id: prettier
                additional_dependencies:
                    - prettier@2.8.6
                types_or: [css, javascript, ts, vue]
                args:
                    [--config frontend/.prettierrc,--write]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
